apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app rathena-renewal
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - config-pvc.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: entrypoint-sh
    files:
      - entrypoint.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
