apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - guacamole.yaml
  - proxmox.yaml
  - synology-dsm.yaml
  - synology-ygg.yaml
  - synology-file.yaml
  - synology-photos.yaml
  - synology-drive.yaml
  - portainer.yaml
  - phpmyadmin.yaml
    #- plex.yaml
  - omoikane-ldap.yaml
  - overseerr-oidc.yaml
  - overseerr-oidc2.yaml
